#!/bin/bash
function status {
  $1
  if [ $? == "0" ]
    then
      echo echo $2 " => OK"
    else
      echo echo $(( $2 )) " => error"
      exit 1
  fi
}
function stop {
  $(status "service apache2 stop" "apache stop")
  $(status "service mysql stop" "mysql stop")
}
function start {
  $(status "service mysql start" "mysql start")
  $(status "service apache2 start" "apache start")
}
if [ $1 == "start" ]
  then
    start
elif [ $1 == "restart" ]
  then
    stop
    start
elif [ $1 == "stop" ]
  then
    stop
fi
